from random import seed, choice
from datetime import datetime

words = {"liquid crystal display": "жидкокристаллический дисплей",
         "cathode ray tube": "катодно-лучевая трубка",
         "organic light-emitting diode": "органический светодиод",
         "performance": "производительность",
         "floppy disk": "дискета",
         "transistor": "транзистор",
         "integrated circuits": "интегральные схемы / микросхемы",
         "graphical user interface": "графический интерфейс пользователя",
         "vacuum tubes": "лампы",
         "compatible": "совместный",
         "energy consumption": "потребление энергии",
         "feature": "особенность",
         "supercomputer": "суперкомпьютер",
         "mainframe": "мейнфрейм",
         "built-in webcam": "встроенная камера",
         "desktop PC": "стационарный компьютер",
         "laptop": "ноутбук",
         "tablet": "планшет",
         "smartphone": "смартфон",
         "battery pack": "аккумуляторная батарея",
         "touch screen": "сенсорный экран",
         "touchpad": "сенсорная панель",
         "usb port": "usb порт",
         "portable devices": "портативные устройства",
         "wearable computer": "носимый на себе компьютер (смарт часы)",
         "digital": "цифровой",
         "multi-tasking": "многозадачный",
         "virtual keyboard": "виртуальная клавиатура",
         "detached keyboard": "физическая клавиатура",
         "central processing unit": "центральный процессор",
         "clock speed": "тактовая частота",
         "system clock": "тактовый генератор",
         "arithmetic logic unit": "арифметико-логическое устройство",
         "control unit": "устройство управления",
         "program counter": "программный счетчик",
         "instruction register": "регистр инструкции",
         "storage devices": "устройства хранения данных",
         "input devices": "устройства ввода",
         "output devices": "устройства вывода",
         "calculations": "вычисления",
         "multi-core CPU": "многоядерный процессор (процессор аббревиатурой)",
         "semiconductor": "полупроводник",
         "silicon": "кремний",
         "front side bus": "фронтальная шина",
         "platters": "пластины",
         "cache": "кэш",
         "cache hit": "попадание в хэш",
         "cache coherency": "когерентность хэша",
         "write-through cache": "кэш со сквозной записью",
         "write-back cache": "кэш с обратной записью",
         "ram": "оперативное запоминаюещее устройство (аббревиатурой)",
         "volatile": "энергозависимый",
         "non-volatile": "энергонезависимый",
         "expansion card": "карта расширения",
         "expansion slots": "слоты расширения",
         "read only memory": "постоянное запоминающее устройство",
         "cloud computing": "облачные вычисления",
         "bus": "шина",
         "solid state drive": "what 'ssd' stands for?",
         "universal serial bus": "what 'usb' stands for?",
         "motherboard": "материнская плата",
         "hard disk drive": "what 'hdd' stands for?",
         "make a backup": "сделать резервную копию",
         "blu-ray disc": "blu-ray диск",
         "laser beam": "лазерный луч",
         "memory capacity": "объем памяти",
         "access time": "время доступа",
         "transfer rate": "скорость передачи данных",
         "compact disc recordable": "what 'cd-r' stands for?",
         "compact disc read only memory": "what 'cd-rom' stands for?",
         "compact disc rewritable": "what 'cd-rw' stands for?",
         "compact disc read only memory": "компакт-диск с возможностью только чтения",
         "flash drive": "флэшка",
         "floating gate transistor": "транзистор с плавающим затвором",
         "aspect ratio": "соотношение сторон",
         "an entry in the directory": "запись в каталоге",
         "cluster": "кластер",
         "sector": "сектор",
         "dvd drive": "DVD-привод",
         "dvd recorder": "DVD-рекордер",
         "particle": "частица",
         "basic input/output system": "what 'BIOS' stands for?",
         "registers": "регистры",
         "external hard disk drive": "внешний жесткий диск",
         "output device": "устройство вывода информации",
         "headphones": "наушники",
         "input device": "устройство ввода информации",
         "memory card": "карта памяти",
         "peripherals": "подключаемое оборудование",
         "power-supply unit": "блок питания",
         "punched card": "перфокарта",
         "speakers": "колонки",
         "storage medium": "носитель информации",
         "system unit": "системный блок",
         "storage device": "устройство хранения данных",
         "usb-flash drive": "флэш-накопитель",
         "platter": "пластина жесткого диска",
         "track": "дорожка на CD/жестком диске",
         "read-write head": "дорожка чтения/записи",
         "head crash": "авария головки (поломка магнитной головки)",
         "windows icons menus pointer": "окна, иконки, меню, указатель",
         "drop-down menu": "расскрывающееся меню",
         "relational database": "реляционная база данных",
         "rendering": "визуализация",
         "scroll bar": "зона прокрутки; линейка прокрутки; полоса прокрутки",
         "nested folders": "вложенные папки",
         "hyperlinks": "гиперссылки",
         "virtual reality": "виртуальная реальность",
         "command driven OS": "ОС, управляемая командами",
         "command line interface": "What 'cli' stands for?",
         "resident program": "завершенная программа",
         "non-resident program": "незавершенная программа",
         "supervisor program": "организующая программа",
         "defragmentation": "дефрагментация",
         "fragmentation": "фрагментация",
         "formatting": "форматирование",
         "command prompt": "командная строка",
         "open-source software": "ПО с открытым исходным кодом",
         "folders": "папки",
         "directory": "каталог",
         "partition": "раздел на жестком диске",
         "random access memory": "оперативная память",
         "software": "программное обеспечение",
         "memory allocation": "выделение памяти",
         "real-time operating systems": "операционные системы реального времени",
         "cooperative multi-tasking": "кооперативная многозадачность",
         "preemptive multi-tasking": "вытесняющая многозадачность",
         "preemptive program": "вытесняющая программа",
         "proprietary software": "закрытое программное обеспечение",
         "timesharing operating system": "операционная система с разделением времени",
         "real-time OS": "операционная система реального времени (операционная система аббривиатурой)",
         "application code": "код приложения",
         "nand": "схема 'И НЕ'",
         "not and gate": "what 'nand' stands for?",
         "nor": "схема 'ИЛИ НЕ'",
         "processor time": "процессорное время",
         "desktop operating system": "настольная операционная система",
         "solid state technology": "твердотельная технология",
         "word processor": "текстовый редактор",
         "spreadsheets": "электронные таблицы",
         "database": "база данных",
         "presentation program": "программа призентации",
         "email": "электронная почта",
         "wireframe": "каркасный",
         "application": "приложение",
         "augmented reality": "дополненная реальность",
         "application server provider": "what 'asp' stands for?",
         "remote access": "удаленный доступ",
         "package": "пакет",
         "mailmerging": "слияние почты",
         "default button": "стандатная кнопка",
         "network topology": "топология сети",
         "bus topology": "топология общей шины",
         "star topology": "топология звезды",
         "mesh topology": "топология сетки (многосвязная сеть)",
         "ring topology": "кольцевая топология",
         "peer-to-peer network": "одноранговая сеть",
         "architecture": "архитектура",
         "wireless local area network": "беспроводная локальная сеть",
         "wide area network": "what 'wan' stands for?",
         "local area network": "локальная сеть",
         "metropolitan area network": "городская сеть",
         "personal area network": "персональная сеть",
         "bridge": "мост",
         "gateway": "шлюз",
         "adapter": "адаптер",
         "protocol": "протокол",
         "hub": "концентратор или повторитель",
         "switch": "переключатель",
         "twisted-pair cable": "витая пара (кабель для интернета, напрямую соединенный со стационарным)",
         "wireless network": "беспроводная сеть",
         "backbone": "магистраль",
         "router": "маршрутизатор",
         "modem": "модем",
         "analog and digital signals": "аналоговый и цифровой сигналы",
         "asynchronous transmission": "асинхронная передача данных",
         "synchronous transmission": "синхронная передача данных",
         "packet switching": "пакетная коммунитация ( передача данных )",
         "broadband": "широкополосный интернет",
         "hot spot": "общая точка доступа",
         "access point": "локальная точка доступа",
         "optical fabe" : "оптоволокно"}


def check(n: int):
    right = n
    t = datetime.now().time()
    seed((t.hour * 60 + t.minute) * 60 + t.second)
    my_words = list(words.keys())
    for i in range(min(n, 180)):
        pair = choice(my_words)
        print(f"{i + 1}) {words[pair]}")
        s = input()
        if s != pair:
            right -= 1
            print("You're wrong! Right answer is: '" + pair + "'")
        my_words.remove(pair)
    return right


def main():
    print("Num of terminus (1-183): ", end="")
    n = int(input())
    print(f"Result: {check(n)}/{n}")


main()
